name: Build

on:
  push:
    branches:
      - '**' # Ignore tags. Build only for pushed commits.

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16.0,17.0)'
          # Visual Studio 2019
          
      - name: Checkout
        uses: actions/checkout@v2.3.3
      
      - name: Update dependencies
        run: msbuild.exe /target:clean,restore
      
      - name: Decode signing certificate
        run: |
            $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.SIGNING_CERT }}")
            $currentDirectory = Get-Location
            $certificatePath = Join-Path -Path $currentDirectory -ChildPath "fast-file.pfx"
            [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
            $pwd = ConvertTo-SecureString "${{ secrets.SIGNING_CERT_PWD }}" -asplaintext -force
            Import-PfxCertificate -FilePath $certificatePath -CertStoreLocation "Cert:\CurrentUser\My" -Password $pwd

      - name: MSBuild Debug
        working-directory: .
        run: msbuild.exe QuickFile.sln /p:Configuration=Debug /target:build
        #/p:AssemblyOriginatorKeyFile "fast-file.pfx" /p:PackageCertificatePassword="${{ secrets.SIGNING_CERT_PWD }}"
        #/target:clean;build;publish /p:ApplicationVersion=<VERSION> /p:SignAssembly=true /p:GenerateManifests=true /p:SignManifests=true /p:AssemblyOriginatorKeyFile=<PFX_PATH> /p:ManifestCertificateThumbprint=<CERTIFICATE_ID> /property:Configuration=<CONFIGURATION>;PublishDir=<PUBLISH_DIR>;BootstrapperEnabled=true;PublishUrl=<PUBLISH_URL>;InstallUrl=<INSTALL_URL>;UpdateUrl=<UPDATE_URL>

      - name: MSBuild Release
        working-directory: .
        run: msbuild.exe QuickFile.sln /p:Configuration=Release /target:build
        #"fast-file.pfx" /p:PackageCertificatePassword="${{ secrets.SIGNING_CERT_PWD }}"
      
      - name: MSBuild publish
        working-directory: .
        run: msbuild.exe QuickFile.sln /p:Configuration=Release /target:publish /p:ApplicationVersion="0.0.0.${{ github.run_number }}" /property:PublishDir="publish\" 
       
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
            name: publish
            path: publish/