name: Build release

on:
  [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16.0,17.0)'
          # Visual Studio 2019
          
      - name: Checkout
        uses: actions/checkout@v2.3.3
      
      - name: Update dependencies
        run: msbuild.exe -t:restore
      
      - name: Decode signing certificate
        run: |
            $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.SIGNING_CERT }}")
            $currentDirectory = Get-Location
            $certificatePath = Join-Path -Path $currentDirectory -ChildPath "fast-file.pfx"
            [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
            Import-PfxCertificate -FilePath "$certificatePath -CertStoreLocation "Cert:\CurrentUser\My" -Password "${{ secrets.SIGNING_CERT_PWD }}"

      - name: MSBuild Debug
        working-directory: .
        run: msbuild.exe QuickFile.sln /p:Configuration=Debug /p:PackageCertificatePassword="${{ secrets.SIGNING_CERT_PWD }}"

      - name: MSBuild Release
        working-directory: .
        run: msbuild.exe QuickFile.sln /p:Configuration=Release /p:PackageCertificatePassword="${{ secrets.SIGNING_CERT_PWD }}"
      
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
            name: publish
            path: publish/