name: Build release

on:
  [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16.0,17.0)'
          # Visual Studio 2019
          
      - name: Checkout
        uses: actions/checkout@v2.3.3
      
      - name: MSBuild Debug
        working-directory: .
        run: msbuild.exe QuickFile.sln /p:Configuration=Debug

      - name: MSBuild Release
        working-directory: .
        run: msbuild.exe QuickFile.sln /p:Configuration=Release
